config/routes.rb
Sticks::Application.routes.draw do
  resources :pitches

  get "welcome/two"
  resources :games

  get "welcome/index"
  get "welcome/redirector"

   root :to => 'welcome#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :pitches
end

app/models/pitch.rb
class Pitch < ActiveRecord::Base
	belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController
  # GET /pitches
  # GET /pitches.json
  def index
    @pitches = Pitch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pitches }
    end
  end

  # GET /pitches/1
  # GET /pitches/1.json
  def show
    @pitch = Pitch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pitch }
    end
  end

  # GET /pitches/new
  # GET /pitches/new.json
  def new
    @pitch = Pitch.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pitch }
    end
  end

  # GET /pitches/1/edit
  def edit
    @pitch = Pitch.find(params[:id])
  end

  # POST /pitches
  # POST /pitches.json
  def create
    @pitch = Pitch.new(params[:pitch])

    respond_to do |format|
      if @pitch.save
        format.html { redirect_to @pitch, notice: 'Pitch was successfully created.' }
        format.json { render json: @pitch, status: :created, location: @pitch }
      else
        format.html { render action: "new" }
        format.json { render json: @pitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pitches/1
  # PUT /pitches/1.json
  def update
    @pitch = Pitch.find(params[:id])

    respond_to do |format|
      if @pitch.update_attributes(params[:pitch])
        format.html { redirect_to @pitch, notice: 'Pitch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pitch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitches/1
  # DELETE /pitches/1.json
  def destroy
    @pitch = Pitch.find(params[:id])
    @pitch.destroy

    respond_to do |format|
      format.html { redirect_to pitches_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if params.key?(:win)
  		@id=params[:id]
 		game=Game.find(@id)
  		game.steps = params[:c].to_i
  		game.winner= params[:win]
  		game.save
  		if params[:win]=="Server"
  			pitch = Pitch.new player: "Browser", sticks: 1, take: 1, game_id: game.id
			pitch.save
		end
  		if (game.save)
  			redirect_to ('/games/' + params[:id])
  		end
  	else
  	end 
	
	@games = Game.limit(10).order("created_at DESC")
	@pitches=Pitch.all
  end
  def gamestable
  end
  def two
  end
  def redirector
	if params[:id].to_i>0
 			@gid=params[:id]
 			game=Game.find(@gid)
 			pitch = Pitch.new player: "Browser", sticks: (params[:a].to_i+params[:b].to_i), take: params[:b].to_i, game_id: game.id
			pitch.save
				
		else
			game = Game.new 
			game.save
			if params[:b].to_i!=0
				pitch = Pitch.new player: "Browser", sticks: (params[:a].to_i+params[:b].to_i), take: params[:b].to_i, game_id: game.id
				pitch.save
			end			
		end

  		@k=params[:a].to_i
		@c=params[:c].to_i
		@c=@c+1

		if (@k==3) 
			@b=2
		elsif ((@k==2)||(@k==1))
		 	@b=1
		else 
			@b=rand(3) + 1
		end

		pitch = Pitch.new player: "Server", sticks: @k, take: @b, game_id: game.id
		pitch.save
		redirect_to ('/welcome/two/'+ '?a=' + (@k-@b).to_s + "&b=" + @b.to_s + "&c=" + @c.to_s + "&id=" + game.id.to_s)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pitches_helper.rb
module PitchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :winner %><br />
    <%= f.text_area :winner %>
  </div>
  <div class="field">
    <%= f.label :steps %><br />
    <%= f.number_field :steps %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      *{
        margin: 0px;
        padding: 0px;
      }
      table, th, td{
        text-align: center;
        border: 2px solid black;
        border-collapse: collapse;
        margin: 0 auto;
        padding: 10px;
      }
      table{
        width: 400px;
      }
      p{
        padding: 2px;
      }
      h1{
        margin: 20px;
      }
      body{
        background-color: #dcf5e1;
      }
      div.osn{
        width: 500px;
        margin: 20px auto;
        text-align: center;
        border: 4px solid #00960e;
        background-color: #b9f5b3;
        border-radius: 10px;
        padding: 0px 20px 20px 20px;
      }      
    </style>
  </head>
  <body>
   <div class="osn">
      <h1>Все игры</h1>
      <table>
        <tr>
          <th>№</th>
          <th>Количество ходов</th>
          <th>Победитель</th>         
        </tr>
      <% @games.each do |game| %>
        <tr>
          <td><%= game.id %></td>
          <td><%= game.steps %></td>
          <td><%if game.winner=="Browser"%>
               <p> Браузер</p>
               <p><%= link_to 'Просмотр ходов', game %></p>
               <p><%= link_to 'Удалить', game, confirm: 'Вы уверены?', method: :delete %></p>
              <% else %>
                <p>Сервер</p>
                <p><%= link_to 'Просмотр ходов', game %></p>
               <p><%= link_to 'Удалить', game, confirm: 'Вы уверены?', method: :delete %></p>
              <% end %>
          </td>          
        </tr>
      <% end %>
      </table>
      <a href="/welcome/index">На главную</a>
    </div>
      </body>
</html>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style>
      table, th, td{
        text-align: center;
        border: 2px solid black;
        border-collapse: collapse;
        margin: 0 auto;
        padding: 5px;
      }
      body{
        background-color: #dcf5e1;
      }
      div.osn{
        width: 500px;
        margin: 20px auto;
        text-align: center;
        border: 4px solid #00960e;
        background-color: #b9f5b3;
        border-radius: 10px;
        padding: 0px 20px 20px 20px;
      }      
      p{
        font-weight: bold;
      }
    </style>
  </head>
  <body>
    <div class="osn">
      <p id="notice"><%= notice %></p>
      <p>Количество ходов:
        <%= @game.steps %></p>
      <p> Победитель:
        <%if @game.winner=="Browser"%>
              Браузер
        <% else %>
              Сервер
        <% end %>
      </p>

      <p>Ходы:</p>
      <table>
        <tr>
          <th>Игрок</th>
          <th>Осталось палочек до хода</th>
          <th>Игрок взял</th>
        </tr>
        <% @game.pitches.each do |pitch| %>
        <tr>
          <td> <%= pitch.player %></td>
          <td><%= pitch.sticks %></td>
          <td> <%= pitch.take%> </td>
         </tr> 
        <% end %>
      </table>
      <%= link_to 'Все игры', games_path %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sticks</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pitches/_form.html.erb
<%= form_for(@pitch) do |f| %>
  <% if @pitch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pitch.errors.count, "error") %> prohibited this pitch from being saved:</h2>

      <ul>
      <% @pitch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :player %><br />
    <%= f.text_area :player %>
  </div>
  <div class="field">
    <%= f.label :sticks %><br />
    <%= f.number_field :sticks %>
  </div>
  <div class="field">
    <%= f.label :take %><br />
    <%= f.number_field :take %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.number_field :game_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pitches/edit.html.erb
<h1>Editing pitch</h1>

<%= render 'form' %>

<%= link_to 'Show', @pitch %> |
<%= link_to 'Back', pitches_path %>

app/views/pitches/index.html.erb
<h1>Listing pitches</h1>

<table>
  <tr>
    <th>Player</th>
    <th>Sticks</th>
    <th>Take</th>
    <th>Game</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pitches.each do |pitch| %>
  <tr>
    <td><%= pitch.player %></td>
    <td><%= pitch.sticks %></td>
    <td><%= pitch.take %></td>
    <td><%= pitch.game_id %></td>
    <td><%= link_to 'Show', pitch %></td>
    <td><%= link_to 'Edit', edit_pitch_path(pitch) %></td>
    <td><%= link_to 'Destroy', pitch, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pitch', new_pitch_path %>

app/views/pitches/new.html.erb
<h1>New pitch</h1>

<%= render 'form' %>

<%= link_to 'Back', pitches_path %>

app/views/pitches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Player:</b>
  <%= @pitch.player %>
</p>

<p>
  <b>Sticks:</b>
  <%= @pitch.sticks %>
</p>

<p>
  <b>Take:</b>
  <%= @pitch.take %>
</p>

<p>
  <b>Game:</b>
  <%= @pitch.game_id %>
</p>


<%= link_to 'Edit', edit_pitch_path(@pitch) %> |
<%= link_to 'Back', pitches_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style type="text/css">
		body{
			background-color: #dcf5e1;
		}
		div.osn{
			width: 300px;
			margin: 20px auto;
			text-align: center;
			border: 4px solid #00960e;
			background-color: #b9f5b3;
			border-radius: 10px;
			padding: 0px 20px 20px 20px;
		}
		</style>
	</head>
	<body>
		<div class="osn">
			<h1>Игра "Палочки"</h1>
			<form>
				<input type="button" id="new" value="Начать игру">
			</form>
				<script>	
				var but=document.getElementById('new')
				but.addEventListener("click",
					function getrandom() { 
						var min_random = 20;
						var max_random = 40;
						max_random++;
						var range = max_random - min_random;
						var k=Math.floor(Math.random()*range) + min_random;
						var choise= Math.random();
							if (choise<=0.5) {
								choise='Браузер';
							}
							else {
								choise='Сервер';
							}
						alert("Количество палочек будет равно " + k +", а игру начнет " + choise);

						if (choise=='Браузер') {
									window.location.assign("/welcome/two/?a=" + k + "&b=" + 0);
								}
								else {
									window.location.assign("/welcome/redirector/?a=" + k + "&b=" + 0);
								}
					},
				 false);
			</script>
			<p><%= link_to 'Все игры', games_path %></p>
	</body>
</html>

app/views/welcome/two.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<style type="text/css">
		body{
			background-color: #dcf5e1;
		}
		div.osn{
			width: 350px;
			margin: 20px auto;
			text-align: center;
			border: 4px solid #00960e;
			background-color: #b9f5b3;
			border-radius: 10px;
			height: 250px;
			padding: 10px;
		}
		.bat{
			height: 30px;
			width: 5px;
			margin: 2px;
			background-color: #00960e;
			float: left;
			border-radius: 2px;
		}
		</style>
	</head>
	<body>
		<div class="osn">
			<script>
				var searchstr=window.location.search.toString();
				var arr=new Array(4);
				var str=searchstr;
				var num=0;
				for(var i=0;i<4;i++){
					num=str.indexOf("=");
					str=str.substr(num+1);
					arr[i]=parseInt(str);
					}	
				count=arr[2];
				document.write('<p>Ход сервера:</p>');
				for (var j=0; j<arr[1]; j++){
					document.write('<div class="bat"></div>');
					}
				document.write('<br>');
				if (arr[0]<=0) {
					alert('Браузер выиграл');
					window.location = '/welcome/index/?win=Browser&c=' + count + '&id=' + arr[3];
					}
				else{
					count++;
					var a;
					var key= Math.random();
					if (arr[0]==3) {
						a=2;
						} 
					else if ((arr[0]==2)||(arr[0]==1)) {
						a=1;
						} 
					else {
						if (key<=0.33) {
							a=1;
						}
						if ((key>0.33)&&(key<0.66)) {
							a=2;
						}
						if (key>0.66) {
							a=3;
						}
					}
					document.write('<p>Ход браузера:</p>');
					for (var j=0; j<a; j++){
						document.write('<div class="bat"></div>');
						}
					document.write('<br>');
					arr[0]=arr[0]-a;
					document.write('<p>Оставшиеся палочки:</p>');
					for (var j=0; j<arr[0]; j++){
						document.write('<div class="bat"></div>');
						}
					if (arr[0]<=0) {
						alert('Сервер выиграл');
						window.location = '/welcome/index/?win=Server&c='+ count + '&id=' + arr[3];
						}
					else {
						window.location = "/welcome/redirector"+ "?a=" + arr[0] + "&b=" + a + "&c=" + count + "&id=" + arr[3];
						}
					}
			</script>
		</div>
	</body>
</html>